[package]
name = "specs_dsl"
version = "0.1.0"
authors = ["Alexander XX <freecoder.xx@gmail.com>"]
edition = "2018"

[dependencies]
specs = { version = "0.15.1", features = ["specs-derive", "shred-derive", "parallel"] }
